#zf210108.1652
# source: 
# https://www.home-assistant.io/getting-started/
# https://www.home-assistant.io/docs/installation/docker/
# https://hub.docker.com/r/linuxserver/code-server
# https://community.home-assistant.io/t/install-vscode-visual-studio-code-as-a-separate-docker-container/166007/33

version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - $PWD/config:/config
    environment:
      - TZ=Europe/Zurich
    restart: always
    ports: 
      - "8123:8123"
    

  vscode:
    container_name: vscode
    image: linuxserver/code-server
    volumes:
      - $PWD/vscode:/config 
      - $PWD:/config/workspace 
    environment:
      - TZ=Europe/Zurich
      - PASSWORD=$ha_vscode_password
#      - SUDO_PASSWORD=xxx
      - PUID=1000
      - PGID=1001
    restart: always
    ports: 
      - "8443:8443"
    
    
    
    
    
    